### PR TITLE
CCCS Update

### PR DESCRIPTION
**Pull request by cccs-kevin**
Hi @ajunius-ANSSI et al.

This is the umbrella PR for all of the changes I've made for this project to fit the use case of the [CCCS](https://github.com/CybercentreCanada). This PR will close open issues and PRs that I've made on this project. Here are the main changes:

- Fixed flag bug in placeholder regular expression logic
- Added lowercase path support in data handler
- Added unit tests for data handler
- Fixed colour argument bug
- Added flag to show a percentage representation of the Markov score in both stdout and the CSV output
- Tweaking .gitignore for all `data`, `model` and `.egginfo` directories
- Updated Numpy version
- Moved `scripts` directory contents to new `anomark` directory (a precursor for the pip package)
- Added a `setup.py` file with author details so that tool can be used as a Python package
- Added output argument to specify file path of CSV output
- Added placeholder capability for hashes (SHA256, SHA1, MD5, file name consisting of truncated hash with 20 chars)
- Added placeholder option for filepaths, which is useful if you use datasets that see all sorts of paths, to the point where they should just be ignored

Next steps:
- I would like this project to be turned into a Pypi package for ease of use in Python code. We can discuss this further on an official channel like email: kevin.hardy-cooper@cyber.gc.ca
- If my logic is flawed regarding the percentage representation of the Markov score relative to the threshold, please let me know and how to fix!

Kevin 🇨🇦

### CODE REVIEW

**Comment by ajunius-ANSSI** [comment]
Hello @cccs-kevin ,
I've reviewed your PR, I am ok with it, except for the percentage. I think the formula must be :  `round(x / prior * 100, 2)`

Until now, I've never added this feature because I thought it could give a false information. It is mainly because we compute a log-likelihood so the scale is not linear. Every model will have a different prior (the minimum value that the log-likelihood could take) so it is difficult to compare them with percentage. But  I am not completely opposed to this idea, if it is clear that it is computed relatively to the model prior.

If you could just modify the formula when it is used, then I will accept the pull request ! :slightly_smiling_face: 

Best regards,
Alexandre

**Comment by cccs-kevin** [comment]
Hi @ajunius-ANSSI! That's great, thanks for taking the time to review my PR, I appreciate it 😄 

Regarding the proposed change to the percentage formula `round(x / prior * 100, 2)`, for my model the `prior` is approximately `1e-8`, so the "percentage" for every value (both anomalies and the usual commands) ends up being very large. Is there a way to handle this?

**Comment by ajunius-ANSSI** [comment]
My bad, because your score is a log-likelihood and the prior is not, you may need to do : `round(x / log(prior) * 100, 2)`

**Comment by ajunius-ANSSI** [comment]
Also, I see that I compute the prior as follow : `self.prior = .01 * min(probabilities)`

Thus, if you wand to get a human readable percentage, you'll need to multiply twice by `100`

**Comment by cccs-kevin** [comment]
> Also, I see that I compute the prior as follow : `self.prior = .01 * min(probabilities)`
> 
> Thus, if you wand to get a human readable percentage, you'll need to multiply twice by `100`

Interesting. I was able to get a human-readable percentage by only multiplying by 100 once. 

I've added commits https://github.com/ANSSI-FR/AnoMark/pull/8/commits/1c68bb8609b6b7955e8df01b4ba58433ad74f941 and https://github.com/ANSSI-FR/AnoMark/pull/8/commits/e4b82e5396c0249d841c8c9f003bf3d8fb2cb027 to fulfill your request here https://github.com/ANSSI-FR/AnoMark/pull/8#issuecomment-1690038818.

Let me know what you think?

**Pull request merged**
